http_server:
  address: "localhost: 8081"
  timeout: 1s
  idle_timeout: 300s

db:
  host: localhost
  port: 5436
  user: postgres
  password: postgres
  name: banners-db

jwt:
  secret: FJKngdjkfgndfkgc534tlLKFJKLmfkdfjnk
default_admin_pass: NJKfsjkdtoierf