#описание среды разворачивания сервера
env: "local"

#параметры сервера
http_server:
  address: "localhost: 8081"
  timeout: 1s
  idle_timeout: 300s
#параметры подключения к базе данных
db:
  host: localhost
  port: 5436
  user: postgres
  password: postgres
  name: banners-db