#описание среды разворачивания сервера
env: "local"
#путь до файлов в которых храниться база данных (!!!это для sql lite потом переделать на postgres) 
storage_path: "./storage/storage.db"
#параметры сервера
http_server:
  address: "localhost: 8081"
  timeout: 1s
  idle_timeout: 300s
db:
  host: localhost
  port: 5436
  user: postgres
  password: postgres
  name: banners-db