#описание среды разворачивания сервера
env: "local"
#путь до файлов в которых храниться база данных (!!!это для dql lite потом переделать на postgres) 
storage_path: "./storage/storage.db"
#параметры сервера
http_server:
  address: "localhost: 8081"
  timeout: 1s
  iddle_timeout: 300s
